#!/bin/bash

# This script only deals with 'x'... use lib for packaging.
LIB=$(echo $2 | sed -e "s/\//\\\\/g;s/\\\\cygdrive\\\\c\\\\/c:\\\\/")
for val in $(lib /NOLOGO /LIST $LIB | tr -d "\r"); do lib /EXTRACT:$val $LIB; done
